### ISSUE TITLE
Displaying suspended meetings

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#110]
Was this by design that meetings marked as location temp suspended AND not online (because there's no URL listed) will not show up on the meeting list? I actually prefer this because suspended meetings with no virtual meeting is ugly on the pages. The reason they're not in draft mode was because some are being reactivated as places open up, and people need to see them if they wanted to. That's why I wanted the default view to be active only, but give folks an option to see inactive ones.

See screenshots. First one is using plugin front-end. Second one is TSML-UI.

![Sunday Meetings - TSML Plugin](https://user-images.githubusercontent.com/62247421/119371134-180ad480-bc84-11eb-8e47-dd60dac5cb6e.jpg)

![Sunday Meetings - TSML UI](https://user-images.githubusercontent.com/62247421/119371170-248f2d00-bc84-11eb-8b2a-ed591208f40b.jpg)

**Comment by joshreisner** [comment]
Yes, that was an intentional change at the time. We (code4recovery) are trying to get the interface right for TSML + TMSL-UI and there is a lot of discussion. It was my contention that inactive meetings should not be displayed at all. I've been persuaded that they should, so now they are showing up again. There is an example at our test site: https://react.meetingguide.org

We now have an "Active" view which web servants can link to in order to hide all the Inactive meetings by default.

I expect this will continue to evolve over the short term, and then hopefully settle down.

**Comment by Grateful-Viv** [comment]
I actually preferred the default to display only active meetings, but with a toggle to display inactive, or all.

>We now have an "Active" view which web servants can link to in order to hide all the Inactive meetings by default.

This is for TSML-UI only?

**Comment by joshreisner** [comment]
You can link to just the Active view on your website, making that the initial view for your users. For example, here are only the active meetings in San Jose: https://react.meetingguide.org/?type=active

We considered hiding inactive meetings by default, but there was a sense among some that most meetings would be going back to Active status soon. 

The sticking point for me was I couldn't think of a way to organize the Any Type menu, it seemed like hiding them would be too inconsistent.

I can't speak for TSML, but my hope is that there will be a similar interface. But we're still working on it.

**Comment by Grateful-Viv** [comment]
What about having active as the default, but giving an option to see all from the dropdown (with a count)?

See my bad image for what I am trying to describe.
![counts-sample](https://user-images.githubusercontent.com/62247421/120072504-3f85e680-c062-11eb-83d9-719bda62aad0.png)

**Comment by joshreisner** [comment]
Thank you for the idea, it gave us something to talk about in our meeting.  

My issue is all the dropdowns have the most inclusive option at the top, and options below that filter / narrow your results in some way. Switching the order would be hard to program, and I think confusing for users, because it would behave differently.

Others in the group think that showing inactive meetings by default is the desired long-term behavior, thinking past the current pandemic situation with widespread closures, when a meeting suddenly becoming inactive is noteworthy enough to alert the fellowship.

To reiterate above, you can make Active be the selected option on your website by linking directly to the active view in your navigation.

**Comment by Grateful-Viv** [comment]
Is it possible to link  just the Active view using the plugin? 

/meetings/?tsml-day=any&tsml-type=active doesn't work.

**Comment by joshreisner** [comment]
It should be once the next update comes out, although the link might look a little different.

The new version is nearly at beta testing stage.

**Comment by Grateful-Viv** [comment]
> You can link to just the Active view on your website, making that the initial view for your users. For example, here are only the active meetings in San Jose: https://react.meetingguide.org/?type=active

What is the shortcode to use with [tsml_react] for opening it with active meetings displaying as the default? Or is that something I have to setup with a hyperlink?
