### ISSUE TITLE
Meeting Detail - Request a Change to this Listing

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#114]
Can this be added back in, or alternatively give us the option to open a form of our choice?

I do see it's available on aasfmarin.org where it says Update Meeting Info.

**Comment by joshreisner** [comment]
The way SF handles this is with a new key I'm [trying to add to the spec](https://github.com/code4recovery/spec/pull/28) called `feedback_url`. The are using a custom solution with Airtable and not using TSML, and they send TSML-UI a special typeform URL in the feed for every meeting.

Google Sheets websites will work out of the box for this too by adding a Feedback URL column, eg https://react.meetingguide.org/demo.html?meeting=cpzh4

Handling this for TSML is tricky. I can think of a few ways, but there are tradeoffs:

1. TSML could provide a feedback screen and add `feedback_url` keys to its data, so that each listing could link to that in a new tab. This should be very effective but a huge amount of work on the WordPress side
2. TSML could provide an API service for TSML-UI for sending feedback emails, this is a huge amount of work on both sides
3. We could identify some really good external plugin or service for handling this and provide instructions, but that becomes a dependency and websites will probably have to pay
4. We could pass TSML feedback emails to TSML-UI in configuration, and that button could be a mailto link. This is by far the easiest approach but means exposing those email addresses to users.

We'll probably want to discuss it internally but let us know if you have a reaction to any of these solutions.

**Comment by Grateful-Viv** [comment]
Could it be something as simple as adding a link to open a form of anyone's choice with the same meeting info passed through on the form (or at least the important info such as meeting name with hyperlink to it)? 

I know many don't even enable this feature and just have a form somewhere on their site that says go here to request a change to your meeting or to add one. That also becomes a dependency on another plugin or service.

**Comment by joshreisner** [comment]
A form of anyone's choice with the meeting info passed through is very complicated! 

I've gone with option 4, so that the Edit Meeting Info button will pop a new email to the feedback emails entered on the Import & Settings page. It will have the page URL in the subject, so the email recipient will know which meeting.

In order for this to work a [pull request I have open](https://github.com/code4recovery/12-step-meeting-list/pull/341) on the plugin will have to be merged.

**Comment by Grateful-Viv** [comment]
I see you're working on this option. Had no idea it was so complicated.

Is it possible to just let us put any text or shortcode or link to whatever the admin wants on the meeting detail page? This ties in to [113](url).
