### ISSUE TITLE
Change Default View to Upcoming Meetings

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#115]
Is this possible?

I noticed upcoming isn't an option to select from the dropdown.  Can this also be put back in.

Thanks.

**Comment by joshreisner** [comment]
The main difference between TSML-UI and TSML is the way it renders meetings in time. I would say TSML-UI's distinguishing feature is that it shows you meetings that are upcoming, so I'm not sure what the request is.

TSML by default shows you all the meetings today (in many places it starts at 6am) and then if it's today you can select Upcoming and that shows you only the meetings going forward today. The main problem (I think) with TSML's upcoming view is that it doesn't wrap around, so if I look at San Jose's upcoming list at 9pm it shows me only one meeting.

TSML-UI is designed to show all the meetings for the week, starting from now. So I see the one upcoming meeting, followed by tomorrow, and then all the rest.

![upcoming](https://user-images.githubusercontent.com/1551689/120057530-acfd2d00-bff8-11eb-85d4-dc41868bf498.png)

What's cool is if I'm in California at 9am and look at the Philadelphia website I should see meeting starting at 12pm, because it accounts for the time difference.

If the above isn't happening for you please share your local development URL so we can investigate.

The feature that's not available is first selecting today from the Any Day dropdown and then using (the missing) Upcoming to isolate it to only the remaining meetings today. I don't think that feature is needed by ordinary people looking for meetings.
