### ISSUE TITLE
Meetings at Same Location Not Correct

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#126]
Not sure if this is a bug.  See https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=friday-night-rehoboth

If you scroll down to where it says St Edmond's Catholic Church, it lists Rehoboth Women Literature (with a link) that is listed at that location. If I open the link and now am at https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=rehoboth-women-literature, there is no mention of the hybrid meeting occurring on Friday at that location (and in-person).

Is it because it's a hybrid? Is it because the Rehoboth Women Literature is only online right now? Then why even display the online meeting when looking at the in-person meeting?

I get that you're not showing addresses crossed off for meetings that moved online (and yes, they may move back in person someday).

Look at https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=midway-closed-discussion. It lists under location two other meetings, one online (used to meet at this location) and the other in-person).

If I go to https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=desire-to-stop, the Midway Closed that's in person is not listed at that location. 

If I go to https://sdi-staging.sussexaa.org/sdi-meetings/?meeting=desire-to-stop-inside, then all three are there.

**Comment by joshreisner** [comment]
This is fixed now. The reason this wasn't working is I had mistakenly thought we shouldn't show location info for meetings that are not in person, so TSML UI hid the section containing the links on the online meeting, but displayed them on the hybrid.

I've switched this back to the old behavior which is only to do that if the address is approximate (no street address). That's the intended situation for meetings that are "natively online" (as opposed to those that have temporarily moved online but still retain a street address because they intend to go back to it).

**Comment by Grateful-Viv** [comment]
Thank you.
