### ISSUE TITLE
Display Meeting Note 

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#128]
Is there an equivalent of this for the UI version?

div#tsml tr.notes a:after { content: "*"; }

**Comment by joshreisner** [comment]
No, this is a pattern that we're trying to get away from. It was originally implemented for SF/Marin, we've since persuaded them that this is bad UI. Users intuitively understand that they can get more information by clicking on the meeting detail, and the visual field becomes cluttered by asterisks everywhere.

@tech2serve has an idea for a timed alert system that will hopefully replace this in cases where there is an urgent temporary message about a particular meeting.
