### ISSUE TITLE
Labels for meeting email & website

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/tsml-ui#135]
Would it be possible to change the text labels in the meeting detail to Group Email (instead of the actual email address) and Group Website or Link (instead of the URL which would get truncated anyway)? 

It’s partially done in the plug-in for email.

see screenshots. first is from the plug-in, second is from the UI. 

![B6336DDE-1EB5-4F03-BA28-596C6F109B9F](https://user-images.githubusercontent.com/62247421/122313310-f946d900-cee3-11eb-9144-637b83209aff.png)

![B66447E8-14E9-4F46-A58A-512600E11623](https://user-images.githubusercontent.com/62247421/122313313-fa780600-cee3-11eb-886c-455b153be750.png)

**Comment by joshreisner** [comment]
As a user I would prefer to know what the button is going to do before I click it. 

If the rationale is security, having the label not display the email address does not hide it from a bot. Here's the code the plugin is using:

```
<a href="mailto:shoreserenity20@gmail.com" class="btn btn-default btn-block group-email">
  <svg class="icon" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383l-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"></path>
  </svg>
  Group Email
</a>
```

For what it's worth, bots can't crawl TSML-UI as easily as they can crawl a regular website, because javascript is required to render the content, and it loads async.

**Comment by Grateful-Viv** [comment]
>As a user I would prefer to know what the button is going to do before I click it.

So would I, and can easily put my cursor over the link to see it displayed on the bottom left side of my browser. But most of our users don't know that and seeing a link such as tiny.one is confusing to them.

The rationale to wanting these labels is not security, but making it easier for the average user to know what these buttons are for.

**Comment by joshreisner** [comment]
tiny.one is a little confusing because of the uncommon .one TLD. since it appears to redirect to https://docs.google.com/document/d/1Sft4FetTOs6JlFeMscvhO7xaiZ51dxwb86fbvtkqJ8A/edit -- I think using that URL instead would tell the user what to expect by clicking the link better than "Group website" or "Link" especially because TSML-UI will display it as docs.google.com
