### ISSUE TITLE
Bug: search with parentheses, asterisks, etc

### ISSUE THREAD

**Issue by FlipperPA** [code4recovery/tsml-ui#177]
If you enter a search term with parentheses, JavaScript throws a wobbly due to escaping:

- Visit https://aasepia.org/
- Enter `(` or `*` in the search box
    - `SyntaxError: Invalid regular expression: /(/: Unterminated group`
    - `Uncaught SyntaxError: Invalid regular expression: /*/: Nothing to repeat`

**Comment by joshreisner** [comment]
ah, that's no good! i see that other special characters are ok, so i guess it's because these have regex significance. what do we think the behavior should be?

1. treat it as normal search text
2. have something special happen logically
3. ignore those characters
4. prevent those characters from being entered

**Comment by joshreisner** [comment]
i went with option 1

**Comment by FlipperPA** [comment]
Thank you, @joshreisner!
