### ISSUE TITLE
Easiest way to *not* list all meetings in sidebar of meeting detail page?

### ISSUE THREAD

**Issue by rockridgefellowship** [code4recovery/tsml-ui#235]
Hi there:

Before I go hacking things up, figured I should ask :):

Using TSML UI, what is the best-practice way to not show the entire list of meetings in the sidebar of the meeting detail page? (edit: just noticed it's listing all meetings twice! Once jjust below location name/address, then again below the venmo link).

I searched here & in what notes I saw but couldn't find a similar issue.
Thanks!
Patrick
<img width="530" alt="Screen Shot 2022-06-23 at 10 42 38" src="https://user-images.githubusercontent.com/101430516/175361585-a6b40cac-2e57-4384-8154-704284b33ba3.png">

**Comment by joshreisner** [comment]
hey, this is expected behavior which is useful on intergroup sites where there are meetings at lots of different locations. the second list is the group-level one, which also makes sense in certain contexts. but i can see how they wouldn't be a good fit for your use-case (one location / one group).

what i can do is add a class selector so you can add some custom css to your site to hide them.

**Comment by rockridgefellowship** [comment]
Ohh, gotcha -- understood! And: perfect! Many thanks @joshreisner 😺

**Comment by joshreisner** [comment]
you should now be able to add CSS to hide those sections:

```
#tsml-ui .location .meetings, #tsml-ui .group .meetings {
  display: none !important;
}
```
