### ISSUE TITLE
Can not add new meetings or edit previous meetings for in person

### ISSUE THREAD

**Issue by DonnaColon** [code4recovery/tsml-ui#279]
Hello, when adding a new meeting or trying to edit an old meeting the location address doesn't seem to be recognized in the map section and doesn't allow publishing until it registers as a valid address however these are valid addresses and even with previous locations the did publish and show on the map do not work now. The image is of an existing meeting edit page the need to be changed on date, however, it doesn't seem to find the address now.
![010523screenshot](https://user-images.githubusercontent.com/78688970/210869657-c44f0405-2100-4201-b3f6-9abaafb18558.jpg)

**Comment by joshreisner** [comment]
hi @DonnaColon , this looks like some other reports we've gotten recently about Google Maps, we recommend either

1. adding the Geocoding API to your Google Maps key in the [API console](https://console.cloud.google.com/), or
2. switch to using [Mapbox](https://www.mapbox.com/) for your maps

most users are finding it easier to do 2 because the Google API Console is pretty complex

**Comment by DonnaColon** [comment]
thank you it worked
