### ISSUE TITLE
Is address/formatted_address required for meetings that are online only?

### ISSUE THREAD

**Issue by tiptop96** [code4recovery/tsml-ui#298]
Not sure if this should be opened here or int the spec, but I discovered it while messing with this repo so here goes.

The spec specifies that meetings require either a `formatted_address` or the components to build one. However for some online meetings this is not applicable.

The meetings which lack either seems to be filtered by the UI.
https://github.com/code4recovery/tsml-ui/blob/f8e8ce853cac456b47a6c5f9c375c9eb3d344705/src/helpers/data/load-meeting-data.ts#L105-L117

So my questions are:
- What would you recommend we do to get our API to be compliant with the spec?
- Is the spec documentation correct (either a `formatted_address` or the components to build one are required) or can online meetings exist without either?

**Comment by joshreisner** [comment]
thanks. we should add something to the API spec's "Common Questions & Concerns" about this. we have had a lot of discussion within AA at the beginning of the pandemic and also guidance provided within 12 Step Meeting List, but i can see how coming from this a different context people could have a different impression

basically, our experience is that online meetings do have _some_ kind of geographic information, even if that is approximate. i'm not sure what your use-case is, but if you were creating a Sweden-wide online meeting finder you could make the `formatted_address` of all meetings be `Sverige`.

the location can be as general or specific as you want, but we recommend it be standardized (geocodable) and it ideally would imply the timezone that the meeting is in. Sometimes it can be useful to think of this as the origin of the meeting, so we often suggest that USA meetings use localities like `Chicago, IL, USA`. This is better than `United States` also because the USA spans several timezones.

**Comment by joshreisner** [comment]
another fine approach if you are doing `Sverige` is to use the `country` key for this

**Comment by tiptop96** [comment]
Thanks for the great input and explanation. The usecase is a platform for the global fellowship so I need a more generic solution but I think I can derive one with the answer you have provided.

To avoid confusion with the terminology, our fellowship uses the structure `Region` > `Area` > `District`. E.g. `Pacific North` > `Washington` > `D2 Snohomish County`. I know others use different labels.

I need to check but think for now we could use areas for this as I think they don't span multiple timezones in my fellowship. Or alternatively get all the parts that are identical for each meeting in a given area. E.g. In Sweden all addresses share `Sverige`, the country, so we could use that. However in the `New York` area they all share country and state, so we could use `New York, USA`. A final option is to have each area figure out a spot and manually enter it.

However we actually have an official `Online` area as well. One way to solve that could be to choose a place which is in the timezone that they use to announce their meetings right? Just shot them a message.

Is the reason for the requirement to give all meetings a TZ so that they can be listed properly depending on the users TZ?

**Comment by joshreisner** [comment]
the requirement is primarily there to help people in recovery find the meetings they want. if i'm shown more than a few options, i would like to know which ones i might share a geographic affinity with.

we find that most meetings do this already. take AA's [Online Intergroup](https://aa-intergroup.org/meetings/) as an example -- so many of these meetings make voluntary reference to geography, without any prompt to do so. i think a valuable improvement for this interface would be to have an "origin" field that groups could use to attract more members.

but yes, also time zones -- services such as the Meeting Guide app should be able to geocode all meetings so it can confirm time zones and geographic coordinates.

my suggested approach (similar to what you're proposing) would be to set a default location field in your database for each Area, and make it optionally available for Districts. `Snohomish County, WA, USA` would be a great default for meetings in that District, but if it were not set, it could fall back to `Washington, USA`.

this might not work though if you have an `Online` area. in which case perhaps you have to have districts? or as a fallback you can derive the location from the timezone? 🤷‍♂️

**Comment by tiptop96** [comment]
I see, that makes sense! Thanks for all your input, super valuable! 👍 

I like your suggestion. I think we'll go that way, having users to specify location per district (optional) and area (required).

I think asking the `Online` area to set up districts is the way to go to keep things simple.

**Comment by tiptop96** [comment]
I'm happy to close the issue if you are?
