### ISSUE TITLE
Customization Request for Meeting Details Screen Link Display

### ISSUE THREAD

**Issue by snakada** [code4recovery/tsml-ui#361]
Hello TSML UI Contributors,

I hope this message finds you well. I would like to suggest a feature enhancement for the Meeting Details screen within the TSML UI. Currently, the full domain name (FQDN) is displayed for web links associated with meetings. This can be somewhat cumbersome, especially for groups that do not have a dedicated website. In our case, we use our server (e.g. https://aajapan-online-intergroup.org/meetings/?meeting=2022-03-0001) to host flyers for such groups, leading to our server's FQDN being displayed.

I propose an option to customize the link display text to something more user-friendly, such as "Click here for the website" or "More information here". This change would not only improve aesthetics but also enhance user experience by providing a clear call-to-action, avoiding any confusion that might arise from seeing a raw FQDN, especially when it points to a generic server hosting various resources.

Thank you for considering this enhancement.

Best regards,

**Comment by snakada** [comment]
Hi @joshreisner, Thanks a lot for getting back to me so quickly!

You're absolutely right; that field is primarily for website URLs. We've been getting creative and using it for flyer links as well. It looks like most of these flyers are provided by our groups in PDF format.

I was thinking, maybe having the links open in a new tab (with target="_blank") or in a modal could be ideal? My concern with inline displays is that they might lead to other important details, like textual information, being missed.

Really appreciate your insight on this matter!

**Comment by joshreisner** [comment]
we can open the URL in a new tab, that makes sense in our normal group-website use-case

i'm still trying to understand the PDF flyer use-case. this seems more like a resource for group servants than something to help normal users find meetings - could you educate me more about their intended use?

**Comment by snakada** [comment]
Thanks for your patience as I clarify this. The PDF flyers are created by individual groups and sent to us (JOI) typically via email. We then host these on our server and link to them from the Meeting Details screen.

The content of these PDF flyers usually includes the group name, its unique features, meeting times, and Zoom ID/PW, among other details.

I hope this helps provide a clearer picture of how and why we use these PDF flyers.

**Comment by joshreisner** [comment]
ok thanks. to follow up - i've confirmed the links already do open in a new tab, so we should be good there. let me know if that's not working for you

at this time, we're not going to move forward with the request to customize the group website buttons with different text. my sense is that when used as intended, linking to an external domain, showing the domain to the user is the most helpful thing to show.

we are discussing internally to what extent we want to also want to also support administrators that wish to use the meeting directory as a resource for group servants, so that supporting materials like group flyers can be added. we want to balance group needs while not distracting users looking for a meeting with secondary materials. and groups that really want to have a way to make documents available can of course start a website

**Comment by snakada** [comment]
Thank you very much for your prompt response, confirmation, and ongoing consideration.

We understand and accept the decision not to proceed with the customization, especially after hearing your explanations. We are also very pleased to learn that you are considering alternative solutions.

We deeply appreciate your continuous effort to consider our needs and improve the service. We look forward to continuing to enjoy your excellent service.

We at JOI will also continue to explore good solutions.

Thank you.
