### ISSUE TITLE
Turn this into a component that can be added via NPM

### ISSUE THREAD

**Issue by billyjacoby** [code4recovery/tsml-ui#58]
Would it be possible to turn this component into a prepackaged NPM component?

I'm currently rebuilding an AA website using Gatsby JS and I would love to be able to just NPM install and import this component into our meeting page, and even add some styles.

This seems pretty doable, and I will begin trying to figure out how to do this on my own. The only concern of mine is that I've never published an NPM package before so I'll have to do a bit of research to figure it all out.

If anyone would like to lend me a hand please let me know!

**Comment by joshreisner** [comment]
Sure, we'd be happy to add it to NPM. In the meantime, you should be able to [import it now straight from Github](https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a).

It's not really designed for this yet, so probably some changes on our side are required. We need to find a way to export the `App` component without looking for a `<script>` tag. If you have any recommendations on how to do this please create a branch and show us. We're happy to make changes if we can serve both purposes.

**Comment by billyjacoby** [comment]
Awesome, thanks Josh. Exporting the app as is was the first hurdle that came to my mind as well.
I'll look into how to accomplish all of this over the next few days and report back what I find.

**Comment by FlipperPA** [comment]
That's great, @billyjacoby - I'm doing something similar for Python/Django: https://pypi.org/project/wagtail-meeting-guide/

**Comment by joshreisner** [comment]
Hi @billyjacoby is this still something you're interested in doing?

**Comment by joshreisner** [comment]
Well, I worked on this a bit with mixed results. By cloning this repo and using `npm link` I was able to import this to a Gatsby project:
```
import TsmlUI from "tsml-ui";
```

and use it like this

```
<TsmlUI json="https://airtable-json.aasfmarin.org" />
```

and despite a deprecation warning it worked!

![gatsby](https://user-images.githubusercontent.com/1551689/119232050-962a7800-bad8-11eb-9ca7-596895d8da44.png)

**However** when I try `yarn add code4recovery/tsml-ui` from the gatsby project then I got a fatal error when I try to run it, it doesn't seem to like JSX.

Not sure what the issue is -- I just don't know enough about making properly exportable modules.
