### ISSUE TITLE
Add filter for next or today to limit records

### ISSUE THREAD

**Issue by 97eighty** [code4recovery/tsml-ui#84]
It would be nice to have react accept some parameters to support displaying next meetings using the 2.0 interface. The Wordpress shortcode [tsml_next_meetings] uses the old interface. 

On sites implementing this short code and the new 2.0 interface it creates two different views.

<meetings src="/path/to/meetings.json" mapbox="pk.aaaaabbbbbcccccd" filter="next" count="40"/>

<meetings src="/path/to/meetings.json" mapbox="pk.aaaaabbbbbcccccd" filter="today"/>

**Comment by FlipperPA** [comment]
Howdy, `tsml-ui` looks for query parameters. For example:

* to show Sunday meetings, include `?weekday=0`. For example: https://aasepia.org/?weekday=0
* to show Monday meetings, include `?weekday=1`. For example: https://aasepia.org/?weekday=1

I think what we might want to do is have the WordPressshortcode pass through any parameters. For example, `[tsml_ui weekday=0 time="midday"]` would call `?weekday=0&time=midday`.

I'm going to go ahead and close this, since I think this should be an issue for the WordPress plugin. Please feel free to reopen if I'm missing something!
