### ISSUE TITLE
Feature: Detect user's timezone

### ISSUE THREAD

**Issue by tintinnabulate** [code4recovery/tsml-ui#93]
Similar to the [online-meeting-list function], it would be handy to detect the visitor's timezone and adjust the displayed meeting time accordingly.

To be clear, I'm requesting two complementary features:

1. A new column in the data set, `timezone`; and,
2. A new feature to automatically adjust the displayed meeting timezone to the timezone the user is currently in.

[online-meeting-list function]: https://github.com/code4recovery/online-meeting-list/blob/434fd0a104faeeb0a4ac99c8ea8bb5a501017135/src/helpers/data.ts#L156

**Comment by joshreisner** [comment]
Could you tell us more about your use-case? What's your website, and what is your service area? I'm curious in particular if your website has meetings that are all in a single timezone or if there is a mix.

TSML UI is somewhat timezone-aware in the sense that if I, a user in San Francisco, visit the [Philadelphia intergroup website](https://aasepia.org) at 8:42am PT, the meeting I see at the top of the list is for 11:45am ET, because it knows that is the next meeting in time.

Is the request to only ever display the time in the user's timezone? So that whenever I visit the Philadelphia website it always displays it in my local timezone? 

If yes, should it tell the user somehow that it's done this? 

Or if not, what would be the mechanism for toggling this on and off?

**Comment by tintinnabulate** [comment]
> Could you tell us more about your use-case? What's your website, and what is your service area? I'm curious in particular if your website has meetings that are all in a single timezone or if there is a mix.

My usecase would be to inherit the feature from the online-meeting-list code, so that I can have a mix of meetings in different timezones normalized to the user's current timezone.

I see that you've committed f105a0bdf46c0bf545230a5ecd9618a87731981a which I haven't taken a look at. What does this implement?


> 
> TSML UI is somewhat timezone-aware in the sense that if I, a user in San Francisco, visit the [Philadelphia intergroup website](https://aasepia.org) at 8:42am PT, the meeting I see at the top of the list is for 11:45am ET, because it knows that is the next meeting in time.
> 
> Is the request to only ever display the time in the user's timezone? So that whenever I visit the Philadelphia website it always displays it in my local timezone?
> 
Yes

> If yes, should it tell the user somehow that it's done this?
> 
The way I do it for the online-meeting-list is to say "All meeting times are in your timezone." - see https://ypaas.netlify.com for an example.

> Or if not, what would be the mechanism for toggling this on and off?

I  think having it always-on is fine, no?
